config/routes.rb
Rails.application.routes.draw do
  resources :books
  resources :students_books
  get 'home/index'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/students_book.rb
class StudentsBook < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:Ma_HS, :Ten_HS, :Lop, :Ma_Sach, :Ten_Sach, :Ten_TacGia, :Tu_Sach, :So_BM, :NgayMuon, :NgayTra, :So_Ngay)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/students_books_controller.rb
class StudentsBooksController < ApplicationController
  before_action :set_students_book, only: %i[ show edit update destroy ]

  # GET /students_books or /students_books.json
  def index
    @students_books = StudentsBook.all
  end

  # GET /students_books/1 or /students_books/1.json
  def show
  end

  # GET /students_books/new
  def new
    @students_book = StudentsBook.new
  end

  # GET /students_books/1/edit
  def edit
  end

  # POST /students_books or /students_books.json
  def create
    @students_book = StudentsBook.new(students_book_params)

    respond_to do |format|
      if @students_book.save
        format.html { redirect_to students_book_url(@students_book), notice: "Students book was successfully created." }
        format.json { render :show, status: :created, location: @students_book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @students_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students_books/1 or /students_books/1.json
  def update
    respond_to do |format|
      if @students_book.update(students_book_params)
        format.html { redirect_to students_book_url(@students_book), notice: "Students book was successfully updated." }
        format.json { render :show, status: :ok, location: @students_book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @students_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students_books/1 or /students_books/1.json
  def destroy
    @students_book.destroy

    respond_to do |format|
      format.html { redirect_to students_books_url, notice: "Students book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_students_book
      @students_book = StudentsBook.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def students_book_params
      params.require(:students_book).permit(:Ma_HS, :Ten_HS, :Lop, :Ma_Sach, :Ten_Sach, :Ten_TacGia)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/students_books_helper.rb
module StudentsBooksHelper
end

app/views/books/_book.html.erb
<tr>
  <th scope="row"><%= index %></th>
  <td><%= book_140.Ma_HS %></td>
  <td><%= book_140.Ten_HS %></td>
  <td><%= book_140.Lop %></td>
  <td><%= book_140.Ma_Sach %></td>
  <td><%= book_140.Ten_Sach %></td>
  <td><%= book_140.Ten_TacGia %></td>
  <td><%= book_140.Tu_Sach %></td>
  <td><%= book_140.So_BM %></td>
  <td><%= book_140.NgayMuon %></td>
  <td><%= book_140.NgayTra %></td>
  <td><%= book_140.So_Ngay %></td>
</tr>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Ma_HS, style: "display: block" %>
    <%= form.text_field :Ma_HS %>
  </div>

  <div>
    <%= form.label :Ten_HS, style: "display: block" %>
    <%= form.text_field :Ten_HS %>
  </div>

  <div>
    <%= form.label :Lop, style: "display: block" %>
    <%= form.text_field :Lop %>
  </div>

  <div>
    <%= form.label :Ma_Sach, style: "display: block" %>
    <%= form.text_field :Ma_Sach %>
  </div>

  <div>
    <%= form.label :Ten_Sach, style: "display: block" %>
    <%= form.text_field :Ten_Sach %>
  </div>

  <div>
    <%= form.label :Ten_TacGia, style: "display: block" %>
    <%= form.text_field :Ten_TacGia %>
  </div>

  <div>
    <%= form.label :Tu_Sach, style: "display: block" %>
    <%= form.text_field :Tu_Sach %>
  </div>

  <div>
    <%= form.label :So_BM, style: "display: block" %>
    <%= form.text_field :So_BM %>
  </div>

  <div>
    <%= form.label :NgayMuon, style: "display: block" %>
    <%= form.datetime_field :NgayMuon %>
  </div>

  <div>
    <%= form.label :NgayTra, style: "display: block" %>
    <%= form.datetime_field :NgayTra %>
  </div>

  <div>
    <%= form.label :So_Ngay, style: "display: block" %>
    <%= form.number_field :So_Ngay %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="w-50 mr-auto text-center font-weight-bold">
  <p>THƯ VIỆN</p>
  <p>TRƯỜNG TIỂU HỌC PHONG THANH TÂY A</p>
</div>
<div class="d-flex">
  <p class="w-75 text-center font-weight-bold">QUẢN LÝ CHO HỌC SINH MƯỢN SÁCH</p>
  <div class="d-flex">
    <span>Quy định ngày quá hạn </span>
    <span class="border-danger border-2">3</span>
  </div>
</div>
<div id="students_books">
  <table class="table">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Ma HS</th>
      <th scope="col">Ten HS</th>
      <th scope="col">Lop</th>
      <th scope="col">Ma Sach</th>
      <th scope="col">Ten Sach</th>
      <th scope="col">Tac Gia</th>
      <th scope="col">Tu Sach</th>
      <th scope="col">So BM</th>
      <th scope="col">Ngay Muon</th>
      <th scope="col">Ngay Tra</th>
      <th scope="col">So Ngay</th>
    </tr>
    </thead>
    <tbody>
    <% i_140 = 1 %>
    <% @books.each do |book_140| %>
      <%= render :partial => 'books/book', :locals => {:index => i_140, :book_140 => book_140}%>
      <% i_140 += 1 %>
    <% end %>
    </tbody>
  </table>
</div>

<%= link_to "New students book", new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <%= link_to "Edit this book", edit_book_path(@book) %> |
  <%= link_to "Back to books", books_path %>

  <%= button_to "Destroy this book", @book, method: :delete %>
</div>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>QUẢN LÝ HỌC SINH CHO MƯỢN SÁCH</title>
</head>
<body>
    <div class="div1">
        <div class="school">
            <h2 class="school_header"> THƯ VIỆN</h2>
            <h2>TRƯỜNG TIỂU HỌC PHONG THẠNH TÂY A</h2>
        </div>
    </div>
    <div class="title">
        <h1>QUẢN LÝ CHO HỌC SINH MƯỢN SÁCH</h1>
        <div class="date">
            <span>Quy định ngày quá hạn</span>
            <div class="ngaymuon">3</div>
        </div>
    </div>
    <div class="table">
        <table>
            <tr>
              <th>TT</th>
              <th>STT</th>
              <th>Mã HS</th>
              <th>Họ và Tên</th>
              <th>Lớp</th>
              <th>Mã sách</th>
              <th>Tên sách</th>
              <th>Tên tác giả</th>
              <th>Tủ sách</th>
              <th>Số BM</th>
              <th>Ngày mượn</th>
              <th>Ngày trả</th>
              <th>Số ngày</th>
              <th>Ghi chú</th>
            </tr>
            <tr>    
                <td></td>
                <td>1</td>
                <td>3b045</td>
                <td>Lê Hồng Ni</td>
                <td>3B</td>
                <td>TN0166</td>
                <td>Vệ sinh ăn uống và giấc ngủ</td>
                <td>Thái Quang Sa dịch</td>
                <td>Thiếu nhi</td>
                <td>1442</td>
                <td>18/09/2017</td>
                <td>21/09/2017</td>
                <td>3</td>
                <td></td>
            </tr>
            <tr>    
                <td></td>
                <td>1</td>
                <td>3b045</td>
                <td>Lê Hồng Ni</td>
                <td>3B</td>
                <td>TN0166</td>
                <td>Vệ sinh ăn uống và giấc ngủ</td>
                <td>Thái Quang Sa dịch</td>
                <td>Thiếu nhi</td>
                <td>1442</td>
                <td>18/09/2017</td>
                <td>21/09/2017</td>
                <td>3</td>
                <td></td>
            </tr>
            <tr>    
                <td></td>
                <td>2</td>
                <td>3b045</td>
                <td>Lê Hồng Ni</td>
                <td>3B</td>
                <td>TN0166</td>
                <td>Vệ sinh ăn uống và giấc ngủ</td>
                <td>Thái Quang Sa dịch</td>
                <td>Thiếu nhi</td>
                <td>1442</td>
                <td>18/09/2017</td>
                <td>21/09/2017</td>
                <td>3</td>
                <td></td>
            </tr>
            <tr>    
                <td></td>
                <td>3</td>
                <td>3b045</td>
                <td>Lê Hồng Ni</td>
                <td>3B</td>
                <td>TN0166</td>
                <td>Vệ sinh ăn uống và giấc ngủ</td>
                <td>Thái Quang Sa dịch</td>
                <td>Thiếu nhi</td>
                <td>1442</td>
                <td>18/09/2017</td>
                <td>21/09/2017</td>
                <td>3</td>
                <td></td>
            </tr>
            <tr>    
                <td></td>
                <td>4</td>
                <td>3b045</td>
                <td>Lê Hồng Ni</td>
                <td>3B</td>
                <td>TN0166</td>
                <td>Vệ sinh ăn uống và giấc ngủ</td>
                <td>Thái Quang Sa dịch</td>
                <td>Thiếu nhi</td>
                <td>1442</td>
                <td>18/09/2017</td>
                <td>21/09/2017</td>
                <td>3</td>
                <td></td>
            </tr>
            <tr>    
                <td></td>
                <td>5</td>
                <td>3b045</td>
                <td>Lê Hồng Ni</td>
                <td>3B</td>
                <td>TN0166</td>
                <td>Vệ sinh ăn uống và giấc ngủ</td>
                <td>Thái Quang Sa dịch</td>
                <td>Thiếu nhi</td>
                <td>1442</td>
                <td>18/09/2017</td>
                <td>21/09/2017</td>
                <td>3</td>
                <td></td>
            </tr>
          </table>
    </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quản lý mượn sách</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <!--  link css js and fontawaresome-->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <!--  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">--> 
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students_books/_form.html.erb
<%= form_with(model: students_book) do |form| %>
  <% if students_book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(students_book.errors.count, "error") %> prohibited this students_book from being saved:</h2>

      <ul>
        <% students_book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Ma_HS, style: "display: block" %>
    <%= form.text_field :Ma_HS %>
  </div>

  <div>
    <%= form.label :Ten_HS, style: "display: block" %>
    <%= form.text_field :Ten_HS %>
  </div>

  <div>
    <%= form.label :Lop, style: "display: block" %>
    <%= form.text_field :Lop %>
  </div>

  <div>
    <%= form.label :Ma_Sach, style: "display: block" %>
    <%= form.text_field :Ma_Sach %>
  </div>

  <div>
    <%= form.label :Ten_Sach, style: "display: block" %>
    <%= form.text_field :Ten_Sach %>
  </div>

  <div>
    <%= form.label :Ten_TacGia, style: "display: block" %>
    <%= form.text_field :Ten_TacGia %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students_books/_students_book.html.erb
<div id="<%= dom_id students_book %>">
  <p>
    <strong>Ma hs:</strong>
    <%= students_book.Ma_HS %>
  </p>

  <p>
    <strong>Ten hs:</strong>
    <%= students_book.Ten_HS %>
  </p>

  <p>
    <strong>Lop:</strong>
    <%= students_book.Lop %>
  </p>

  <p>
    <strong>Ma sach:</strong>
    <%= students_book.Ma_Sach %>
  </p>

  <p>
    <strong>Ten sach:</strong>
    <%= students_book.Ten_Sach %>
  </p>

  <p>
    <strong>Ten tacgia:</strong>
    <%= students_book.Ten_TacGia %>
  </p>

</div>

app/views/students_books/edit.html.erb
<h1>Editing students book</h1>

<%= render "form", students_book: @students_book %>

<br>

<div>
  <%= link_to "Show this students book", @students_book %> |
  <%= link_to "Back to students books", students_books_path %>
</div>

app/views/students_books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students books</h1>

<div id="students_books">
  <% @students_books.each do |students_book| %>
    <%= render students_book %>
    <p>
      <%= link_to "Show this students book", students_book %>
    </p>
  <% end %>
</div>

<%= link_to "New students book", new_students_book_path %>

app/views/students_books/new.html.erb
<h1>New students book</h1>

<%= render "form", students_book: @students_book %>

<br>

<div>
  <%= link_to "Back to students books", students_books_path %>
</div>

app/views/students_books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @students_book %>

<div>
  <%= link_to "Edit this students book", edit_students_book_path(@students_book) %> |
  <%= link_to "Back to students books", students_books_path %>

  <%= button_to "Destroy this students book", @students_book, method: :delete %>
</div>